version: '3'
services:
  mqtt:
    build: ./server
    image: sendlab-mqtt/ubuntu
    container_name: sendlab-mqtt-ubuntu
    ports:
     - "8883:8883"
    command: /bin/bash
    tty: true
    stdin_open: true