version: '3'
services:
  mqtt:
    build: ./mqtt
    image: sendlab-mqtt/ubuntu
    container_name: sendlab-mqtt-ubuntu
    ports:
     - "8883:8883"
    volumes:
     - /var/log/mosquitto:/var/log/mosquitto:rw
    tty: true
    stdin_open: true
  node:
    build: ./
    image: sendlab-node/ubuntu
    container_name: sendlab-node-ubuntu
    ports:
     - "23450:23450"
     - "34219:34219"
     - "8080:8080"
    volumes:
     - /var/log/pm2:/root/.pm2/logs:rw
    tty: true
    stdin_open: true
  mongo:
    build: ./mongodb
    image: sendlab-mongo/ubuntu
    container_name: sendlab-mongo-ubuntu
    volumes:
     - /var/log/mongodb:/var/log/mongodb:rw
     - /data:/data
    tty: true
    stdin_open: true
  visualisatie-zonneboot:
    build: ./visualisatie/zonneboot
    image: sendlab-vis-zonneboot/ubuntu
    container_name: sendlab-vis-zonneboot-ubuntu
    ports:
     - "4200:80"
    tty: true
    stdin_open: true
