version: '3'
services:
  mqtt:
    build: ./mqtt
    image: sendlab-mqtt/ubuntu
    container_name: sendlab-mqtt-ubuntu
    ports:
     - "8883:8883"
    volumes:
     - ./logs/mosquitto:/var/log/mosquitto:rw
    tty: true
    stdin_open: true